FROM node
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ENV REACT_APP_INFLUXDB_IP=ENVFILE
ENV REACT_APP_INFLUXDB_DATABASE=ENVFILE
ENV REACT_APP_INFLUXDB_DATABASE_USER=ENVFILE
ENV REACT_APP_INFLUXDB_DATABASE_PASSWORD=ENVFILE
ENV REACT_APP_URL_API_PROTOCOL=ENVFILE
ENV REACT_APP_URL_API_HOST=ENVFILE
ENV REACT_APP_URL_API_PORT=ENVFILE
EXPOSE 3000

#docker run --env-file ./.env.development --env-file ./.env.production -d -p 3000:3000
# --name farmstech farmstech  

COPY . .
CMD ["npm", "run", "start"]
